apiVersion: apps/v1
kind: Deployment
metadata:
  name: orhestra-backend-production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: orchestra-backend-production
  template:
    metadata:
      labels:
        app: orch-backend
    spec:
      containers:
        - name: orchestra-backend-production
          image: orchestra-backend-production
          imagePullPolicy: Never
          ports:
            - containerPort: 8282
