// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customer.sql

package dbq

import (
	"context"
)

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO "orchestra-table" (customer_id, first_name, last_name, created_at)
VALUES ($1, $2, $3, CURRENT_TIMESTAMP)
RETURNING customer_id, first_name, last_name, created_at
`

type CreateCustomerParams struct {
	CustomerID string
	FirstName  string
	LastName   string
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (OrchestraTable, error) {
	row := q.db.QueryRow(ctx, createCustomer, arg.CustomerID, arg.FirstName, arg.LastName)
	var i OrchestraTable
	err := row.Scan(
		&i.CustomerID,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
	)
	return i, err
}

const customerExists = `-- name: CustomerExists :one
SELECT EXISTS(SELECT 1 FROM "orchestra-table" WHERE first_name = $1 AND last_name = $2)
`

type CustomerExistsParams struct {
	FirstName string
	LastName  string
}

func (q *Queries) CustomerExists(ctx context.Context, arg CustomerExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, customerExists, arg.FirstName, arg.LastName)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getCustomerByID = `-- name: GetCustomerByID :one
SELECT customer_id, first_name, last_name, created_at
FROM "orchestra-table"
WHERE customer_id = $1
LIMIT 1
`

func (q *Queries) GetCustomerByID(ctx context.Context, customerID string) (OrchestraTable, error) {
	row := q.db.QueryRow(ctx, getCustomerByID, customerID)
	var i OrchestraTable
	err := row.Scan(
		&i.CustomerID,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
	)
	return i, err
}

const getCustomerByName = `-- name: GetCustomerByName :one
SELECT customer_id, first_name, last_name, created_at
FROM "orchestra-table"
WHERE first_name = $1 AND last_name = $2
LIMIT 1
`

type GetCustomerByNameParams struct {
	FirstName string
	LastName  string
}

func (q *Queries) GetCustomerByName(ctx context.Context, arg GetCustomerByNameParams) (OrchestraTable, error) {
	row := q.db.QueryRow(ctx, getCustomerByName, arg.FirstName, arg.LastName)
	var i OrchestraTable
	err := row.Scan(
		&i.CustomerID,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
	)
	return i, err
}

const listCustomers = `-- name: ListCustomers :many
SELECT customer_id, first_name, last_name, created_at
FROM "orchestra-table"
ORDER BY created_at DESC
`

func (q *Queries) ListCustomers(ctx context.Context) ([]OrchestraTable, error) {
	rows, err := q.db.Query(ctx, listCustomers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrchestraTable{}
	for rows.Next() {
		var i OrchestraTable
		if err := rows.Scan(
			&i.CustomerID,
			&i.FirstName,
			&i.LastName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
