// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbq

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type OrchestraTable struct {
	CustomerID string
	FirstName  string
	LastName   string
	CreatedAt  pgtype.Timestamp
}
