// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbq

import (
	"context"
)

type Querier interface {
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (OrchestraTable, error)
	CustomerExists(ctx context.Context, arg CustomerExistsParams) (bool, error)
	GetCustomerByID(ctx context.Context, customerID string) (OrchestraTable, error)
	GetCustomerByName(ctx context.Context, arg GetCustomerByNameParams) (OrchestraTable, error)
	ListCustomers(ctx context.Context) ([]OrchestraTable, error)
}

var _ Querier = (*Queries)(nil)
